version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  api_gateway:
    build: services
    container_name: api_gateway
    restart: always
    depends_on:
      - users_service
    ports:
      - "8080:80"
    volumes:
      - ./services/api_gateway:/var/www/html
    command: bash -c "composer install && cp .env.example .env && chmod 777 -R ./storage && php artisan jwks:load && apache2-foreground"

  users_service:
    build: services
    container_name: users_service
    restart: always
    ports:
      - "8060:80"
    depends_on:
      - postgres
    volumes:
      - ./services/users_service:/var/www/html
    command: bash -c "composer install && cp .env.example .env && chmod 777 -R ./storage && php artisan jwks:generate && php artisan migrate:refresh --seed && apache2-foreground"

  p2p_chat_service:
    build: services
    container_name: p2p_chat_service
    restart: always
    ports:
      - "8050:80"
    depends_on:
      - postgres
    volumes:
      - ./services/p2p_chat_service:/var/www/html
    command: bash -c "composer install && cp .env.example .env && chmod 777 -R ./storage && php artisan jwks:load && php artisan migrate:refresh --seed && apache2-foreground"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db-data: