version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  api_gateway:
    build: services
    container_name: api_gateway
    restart: always
    depends_on:
      - users_service
    ports:
      - "8080:80"
    volumes:
      - ./services/api_gateway:/var/www/html
    command: bash -c "composer install && cp .env.example .env && chmod 777 -R ./storage/logs && php artisan jwks:load && apache2-foreground"

  users_service:
    build: services
    container_name: users_service
    restart: always
    ports:
      - "8060:80"
    depends_on:
      - postgres
    volumes:
      - ./services/users_service:/var/www/html
    command: bash -c "composer install && cp .env.example .env && chmod 777 -R ./storage/logs && php artisan jwks:generate && php artisan migrate:refresh --seed && apache2-foreground"

  p2p_chat_service:
    build: services
    container_name: p2p_chat_service
    restart: always
    ports:
      - "8050:80"
    depends_on:
      - postgres
    volumes:
      - ./services/p2p_chat_service:/var/www/html
    command: bash -c "composer install && cp .env.example .env && chmod 777 -R ./storage/logs && php artisan jwks:load && apache2-foreground"


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
volumes:
  db-data: